export const UPDATE_RESOURCE_POOL_LIST = 'UPDATE_RESOURCE_POOL_LIST';
export const UPDATE_RESOURCE_POOL_LIST_LOADING = 'UPDATE_RESOURCE_POOL_LIST_LOADING';
export const UPDATE_RESOURCE_POOL_LIST_PAGINATION = 'UPDATE_RESOURCE_POOL_LIST_PAGINATION'; 