export const UPDATE_MAINTENANCE_LIST = 'UPDATE_MAINTENANCE_LIST';
export const UPDATE_MAINTENANCE_LIST_LOADING = 'UPDATE_MAINTENANCE_LIST_LOADING';
export const UPDATE_MAINTENANCE_LIST_PAGINATION = 'UPDATE_MAINTENANCE_LIST_PAGINATION'; 