
export const UPDATE_ORACLE_LIST = 'UPDATE_ORACLE_LIST';
export const UPDATE_ORACLE_LIST_LOADING = 'UPDATE_ORACLE_LIST_LOADING';

export const UPDATE_MYSQL_LIST = 'UPDATE_MYSQL_LIST';
export const UPDATE_MYSQL_LIST_LOADING = 'UPDATE_MYSQL_LIST_LOADING';