export const UPDATE_IP_DIMENSIONS_RELATION = 'UPDATE_IP_DIMENSIONS_RELATION';
export const UPDATE_IP_DIMENSIONS_RELATION_PAGINATION = 'UPDATE_IP_DIMENSIONS_RELATION_PAGINATION';
export const UPDATE_IP_DIMENSIONS_RELATION_LOADING = 'UPDATE_IP_DIMENSIONS_RELATION_LOADING';
export const UPDATE_IP_DIMENSIONS_DETAILS = 'UPDATE_IP_DIMENSIONS_DETAILS';
export const UPDATE_IP_DIMENSIONS_DETAILS_LOADING = 'UPDATE_IP_DIMENSIONS_DETAILS_LOADING';
export const UPDATE_IP_DIMENSIONS_DETAILS_OTHER = 'UPDATE_IP_DIMENSIONS_DETAILS_OTHER';

export const UPDATE_DATABASE_INSTANCE_LIST = 'UPDATE_IDATABASE_INSTANCE_LIST';
export const UPDATE_DATABASE_INSTANCE_LIST_LOADING = 'UPDATE_IDATABASE_INSTANCE_LIST_LOADING';
export const UPDATE_DATABASE_INSTANCE_IP_LIST = 'UPDATE_IDATABASE_INSTANCE_IP_LIST';
export const UPDATE_DATABASE_INSTANCE_IP_LIST_LOADING = 'UPDATE_IDATABASE_INSTANCE_IP_LIST_LOADING';
export const UPDATE_DATABASE_INSTANCE_IP_LIST_PAGINATION = 'UPDATE_IDATABASE_INSTANCE_IP_LIST_PAGINATION';
