export const UPDATE_CONTRACT_LIST = 'UPDATE_CONTRACT_LIST';
export const UPDATE_CONTRACT_LIST_LOADING = 'UPDATE_CONTRACT_LIST_LOADING';
export const UPDATE_CONTRACT_LIST_PAGINATION = 'UPDATE_CONTRACT_LIST_PAGINATION'; 